version = 0.1

[prod.deploy.parameters]
stack_name = "pokemon-api"
resolve_s3 = true
s3_prefix = "pokemon-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiStageName=prod"
disable_rollback = true
