spring:
  application:
    name: pokemon-api
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: local

dynamodb:
  region: us-east-1
  endpoint: http://localhost:8000
  access-key: fake
  secret-key: fake
  tables:
    capture-pokemon: pokemon-api-capture-local
    users: pokemon-api-users-local
    connections: pokemon-api-connections-local
    battles: pokemon-api-battles-local

websocket:
  endpoint: http://localhost:9999

pokeapi:
  url: https://pokeapi.co/api/v2

logging:
  level:
    org.springframework.data.redis: DEBUG