name: Deploy Lambda AWS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace environment variables in template
        run: |
          sanitize() {
            printf '%s' "$1" | tr -d '\n' | sed 's/[\/&|]/\\&/g'
          }
          sed -i "s|!Ref appName|$(sanitize "${{ secrets.APP_NAME }}")|g" template.yaml

      - name: Create env file
        run: |
          cat <<EOF > .env
          APP_NAME=${{ secrets.APP_NAME }}
          EOF

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_CLOUD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CLOUD_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_CLOUD_REGION_PROD }}

      - name: Generate Maven Wrapper
        run: mvn -N io.takari:maven:wrapper

      - name: Build GraalVM Docker image
        run: docker build -t al2023-graalvm21:native-web .

      - name: Build native image inside Docker
        run: |
          docker run --rm \
            --env-file .env \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -v ~/.m2:/root/.m2 \
            al2023-graalvm21:native-web \
            ./mvnw clean -Pnative package -DskipTests

      - name: List target folder
        run: ls -lah target

      - name: SAM Build
        run: sam build --use-container

      - name: SAM Deploy
        run: |
          sam deploy \
            --no-confirm-changeset \
            --config-file samconfig.toml \
            --config-env prod \
            --no-fail-on-empty-changeset \
            --stack-name pokemon-api \
            --resolve-s3 \
            --parameter-overrides CognitoClientId=${{ secrets.CLIENT_ID }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_CLOUD_REGION_PROD }}